# Generated by Django 3.1.1 on 2020-11-30 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='dateBought',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopuser',
            name='just_bought',
            field=models.CharField(default='apples', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopuser',
            name='lst',
            field=models.CharField(default='milk', max_length=200),
            preserve_default=False,
        ),
    ]
