# Generated by Django 3.1.1 on 2020-12-03 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201130_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='dateBought',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='date_bought',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
