# Generated by Django 3.1.1 on 2020-12-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201203_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='recipes',
            field=models.CharField(default='lololol', max_length=200),
        ),
    ]
