# Generated by Django 3.1.1 on 2020-12-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201209_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='recipe_names',
            field=models.CharField(default='["empty", "empty", "empty", "empty", "empty", "empty", "empty"]', max_length=200),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='recipes',
            field=models.CharField(default='["empty", "empty", "empty", "empty", "empty", "empty", "empty"]', max_length=200),
        ),
    ]
